Mage2Gen/Mage2Gen

mage2gen/snippets/__init__.py
mage2gen/snippets/customerattribute.py
mage2gen/snippets/system.py
mage2gen/templates/attributes/customeraddressattribute.tmpl
mage2gen/templates/attributes/customerattribute.tmpl

Customer attribute snippet, system snippet improvement, sourcemodel

customer attribute snippet, system snippet improvement

---

mage2gen/snippets/categoryattribute.py
mage2gen/snippets/customerattribute.py
mage2gen/snippets/system.py
mage2gen/templates/attributes/customeraddressattribute.tmpl
mage2gen/templates/attributes/customerattribute.tmpl

Improvement,bugfixes on category, customer and system snippet

Improvement,bugfixes on category, customer and system snippet

---

mage2gen/snippets/payment.py

Fixed the type for allowspecific and specificcountry system.xml node for payment method to Magento default

[BUGFIX] Fixed the right types for allowspecific and specificcountry on system.xml configurations for payment method snippet

---

mage2gen/snippets/model.py

Currently, it's hard coded to Experius_Test::top_level.

Fix admin active menu

---

mage2gen/snippets/model.py

Add di.xml preferences

---

mage2gen/snippets/productattribute.py

Option to Transport the Product Attribute to the Quote Item

[FEATURE] Updated the Product Attribute Snippet

---

mage2gen/snippets/__init__.py
mage2gen/snippets/block.py

Available Options
Classname
Methodname (is als used in the template)
Scope (Backend or Frontend)
Layout handle (not required)
Reference type (depends on Layout handle)
Reference name (depends on Layout handle)

[TASK] Added New Block Snippet | Just a Block

---

mage2gen/snippets/observer.py

[FEATURE] Added webapi as scope to the Observer / Event Snippet

---

mage2gen/snippets/plugin.py

[FEATURE] Added Scope option to the Plugin Snippet

---

mage2gen/snippets/model.py
mage2gen/utils.py

[BUGFIX] Updated the Params and DocStrings with correct CamelCase

---

mage2gen/module.py

[TASK] Added 'magento2-module' as type to the composer.json

---

mage2gen/snippets/categoryattribute.py
mage2gen/snippets/customerattribute.py
mage2gen/snippets/install.py
mage2gen/snippets/productattribute.py

Added this for the following attribute types:
- Customer Attributes
- Customer Address Attributes
- Product Attributes
- Category Attributes

[FEATURE] Added the option to move Attribute Setups to UpgradeData instead of InstallDat

---

mage2gen/templates/payment/payment-method-js.tmpl
mage2gen/templates/payment/payment.tmpl

Add payment instruction paragraph which configured on admin for custom payment method
Will add a paragraph contains instruction text for custom payment method

[FEATURE] Add Payment Instruction for Payment templates

---

mage2gen/snippets/plugin.py

[BACKPORT] [TASK] [issue-194] Check Sequence for Class which the Plugin applies to

---

mage2gen/snippets/__init__.py
mage2gen/snippets/producttype.py
mage2gen/templates/producttype.tmpl

Add Product Type Snippet
**[krukas/Mage2Gen#107](https://github.com/krukas/Mage2Gen/issues/107): Product Type Snippet**
+ This will add Product Type Snippet

[TASK] [issue-107] Add Product Type Snippet

---

mage2gen/snippets/model.py

Magento\\Framework\\Api\\ExtensionAttribute\\JoinProcessorInterface

[BUGFIX] Removed breaking slash in dependency

---

mage2gen/snippets/model.py

@tuyennn Tested it and needed to add some extra stuff to make it work. This should be the final version. @lewisvoncken Can you review the pull request?

Issue 153 Seperate DataModel Fixes

---

mage2gen/license.py
mage2gen/licenses/apache2.txt
mage2gen/licenses/apache2_short.txt
mage2gen/licenses/gplv3_short.txt
mage2gen/licenses/mit.txt
mage2gen/licenses/oslv3_short.txt

Add MIT and Apache2 License
+ This will add MIT and Apache2 license for user to choose

[TASK][PATCH] Add MIT and Apache2 License

---

mage2gen/__init__.py
mage2gen/module.py
mage2gen/snippet.py
mage2gen/snippets/__init__.py
mage2gen/snippets/graphql.py
mage2gen/snippets/plugin.py
mage2gen/templates/graphqlobject.tmpl
mage2gen/templates/graphqlobjectitem.tmpl
mage2gen/templates/graphqlschema.tmpl

Generates:
- GraphQl Schema
- Resolver Class
- Resolver Data Provider Class when Base Type is Query
- Module Dependency when a dependency is injected to the Resolver Data Provider
Base of Magento Core modules which are test cases: StoreGraphQl, QuoteGraphQl, CmsGraphQl, CatalogGraphQl, BundleGraphQl.

[FEATURE] Added GraphQl Support

---

mage2gen/snippets/plugin.py

This feature is related to issue #242

[FEATURE] [issue-242] Pre-fill the Plugin Variables

---

mage2gen/snippets/__init__.py
mage2gen/snippets/viewmodel.py

[FEATURE] Added ViewModel Snippet

---

mage2gen/snippets/__init__.py
mage2gen/snippets/companyattribute.py
mage2gen/templates/attributes/companyattribute.tmpl

Currently support for input and textarea.

[FEATURE] Added Enterprise Company Attribute Snippet

---

mage2gen/snippets/__init__.py
mage2gen/snippets/saleattribute.py
mage2gen/templates/attributes/sales/attribute.tmpl
mage2gen/templates/attributes/sales/options.tmpl

[FEATURE] Added Sales Attribute Setup Snippet

---

mage2gen/snippets/companyattribute.py

Prevented save of value to company attribute. This is tested in 2.2.5

[BUGFIX] - Value is not a param, but a postvalue

---

mage2gen/snippets/plugin.py

[FEATURE] [issue#258] Added scoping for Plugins

---

mage2gen/snippets/plugin.py

[BACKPORT] [FEATURE] [issue#258] Added scoping for Plugins

---

mage2gen/__init__.py
mage2gen/module.py
mage2gen/snippets/api.py
mage2gen/snippets/block.py
mage2gen/snippets/cache.py
mage2gen/snippets/categoryattribute.py
mage2gen/snippets/companyattribute.py
mage2gen/snippets/configurationtype.py
mage2gen/snippets/console.py
mage2gen/snippets/controller.py
mage2gen/snippets/cronjob.py
mage2gen/snippets/customerattribute.py
mage2gen/snippets/eaventity.py
mage2gen/snippets/eaventityattribute.py
mage2gen/snippets/graphql.py
mage2gen/snippets/helper.py
mage2gen/snippets/model.py
mage2gen/snippets/observer.py
mage2gen/snippets/payment.py
mage2gen/snippets/plugin.py
mage2gen/snippets/productattribute.py
mage2gen/snippets/producttype.py
mage2gen/snippets/saleattribute.py
mage2gen/snippets/shipping.py
mage2gen/snippets/system.py
mage2gen/snippets/viewmodel.py
mage2gen/snippets/widget.py
mage2gen/templates/readme.tmpl

[FEATURE] [issue#302] Added README.md support based on snippets

---

mage2gen/snippets/__init__.py
mage2gen/snippets/customerdata.py

New Snippet: Customer (Section) Data
**[krukas/Mage2Gen#312](https://github.com/krukas/Mage2Gen/issues/312): New Snippet: Customer (Section) Data**
+ Add new snippet

[feature-312]: Add Customer Section Data Snippet

---

mage2gen/snippets/controller.py

Inject the logger so it can be used at
https://github.com/krukas/Mage2Gen/blob/magento-2.3/mage2gen/snippets/controller.py#L117

Inject logger so it can be used.

---

mage2gen/templates/shipping.tmpl

Correcting param and return type pf getAllowedMethods

Correcting docblock

---

mage2gen/snippets/model.py

[FEATURE][issue#339] Added default comment for generated model

---

mage2gen/snippets/producttype.py

[FEATURE][issue#357] Added option use_qty to the Product Type Snippet

---

mage2gen/snippets/model.py

[FEATURE][issue#51] Added extra_param sort_order for the Model Snippet

---

mage2gen/snippets/viewmodel.py

Argument name should be "view_model"

Fix viewmodel layout argument definition

---

mage2gen/snippets/eaventityattribute.py

array() => [] as per modern coding style rules

Use short array syntax

---

mage2gen/templates/pagebuilder/preview.tmpl

Replaced self-closing render element with an render element with a closing tag.

Update preview.tmpl. Replaced self-closing render element
