mage2gen/snippets/payment.py

When create a payments module, the isAvailable method not contains semicolon.

[BUGFIX]  Semicolon correction

---

mage2gen/snippets/payment.py

When create a payments module, the system config field label for node active and order_status was inverted, causing confusions on admin configuration.

[BUGFIX] Fixed system.xml config field label for Enabled and New Order Status on Payment Method generator

---

.travis.yml

Python 3.6 has been released. We should add it to the Travis test-suite.

[TASK] Add python 3.6 to travis testing suite.

---

mage2gen/snippets/model.py

Currently, the Repository returns an array of arrays but it's easier and nicer to deal with objects.

Repository, getList(): return objects instead of arrays

---

.travis.yml

With moving to the Trusty distro and use the manual method to install php it's fixed.
Closes #73

[TASK] Move travis distribution to trusty + sudo (Fix tests).

---

mage2gen/snippets/model.py

Hello,
The model name was used instead of the module one, so it didn't work if the module and model names were different

Fix module name instead or model name

---

mage2gen/snippets/productattribute.py

Now the product attributes could be applied to the Virtual Magento product as mentioned at https://github.com/krukas/Mage2Gen/issues/94

Virtual product type has been added into the product attribute snippet

---

mage2gen/snippets/block.py

[BUGFIX] [issue-178] Allow dots in the Block Reference Name

---

mage2gen/snippets/model.py

When editing a existing record the title depends on $model->getTitle(). Replace with __('Edit {model_name}')
**[krukas/Mage2Gen#176](https://github.com/krukas/Mage2Gen/issues/176): Model Admin Edit Form Title**
The title should be changed to 
```
__('Edit {model_name} %1', $model->getId())
```

[TASK] [issue-176] Change Model Admin Edit Form Title which doesn't depend on $model->getTitle()

---

mage2gen/snippets/productattribute.py

The leading backslash was missing in the extends part, which means that the AbstractSource class is thought to be like: 
`MyVendor\MyModule\Model\Product\Attribute\Source\Magento\Eav\Model\Entity\Attribute\Source\AbstractSource`

Add leading slash that was missing in 'extends'

---

mage2gen/snippets/model.py

Inline editing for a UI grid component does not work when selection M2.2 module.
If you change two lines, it does:
```
<settings>
<editorConfig>
<param name="selectProvider" xsi:type="string">listing.listing.columns.ids</param>
<param name="enabled" xsi:type="boolean">true</param>
<param name="indexField" xsi:type="string">id_filed</param>
<param name="clientConfig" xsi:type="array">
<item name="saveUrl" path="icrm_report/budgetfigure/inlineEdit" xsi:type="url"/>
<item name="validateBeforeSave" xsi:type="boolean">false</item>
</param>
</editorConfig>
<childDefaults>
<param name="fieldAction" xsi:type="array">
---<item name="provider" xsi:type="string">listing.listing.columns_editor</item>
+++<item name="provider" xsi:type="string">listing.ilisting.columns.actions</item>
---<item …
```

[TASK] [issue-223] Fix Magento 2.2, 2.3 inline edit on wrong node text

---

mage2gen/snippets/graphql.py

The generated code can't be used as the Query definition references the lower case type name
```
type Query {
posts (
...
): posts  @resolver(...
}
```
When the main Type definition is uppercase first
```
type Posts {
...
}
```
Results in 
```
1 exception(s):
Exception #0 (GraphQL\Error\Error): Type "posts" not found in document.
```
Fixed by passing the item_type param for Query types as the uppercasefirst item_identifier resulting in 
```
type Query {
posts (
...
): Posts  @resolver(
}
```

[BUGFIX] Incorrect GraphQl schema Query Type identifier used

---

mage2gen/snippets/widget.py

Wrong generated static phtml widget snippet
Both will be converted to lower case.
**[krukas/Mage2Gen#248](https://github.com/krukas/Mage2Gen/issues/248): widget template name issue**
+ Both will be converted to lower case.

[TASK][issue-248] Fix wrong generated static phtml widget snippet

---

mage2gen/snippets/productattribute.py
mage2gen/templates/attributes/productattribute.tmpl

This patch will add **swatch_visual** and **swatch_text** to current product attribute snippet.
+ Default value for color swatch
'Black' => '#000000', 'White' => '#ffffff'
+ Default value for text swatch
'Sample' => 'Sample'

[TASK] [PATCH] Add swatch types for product attributes

---

mage2gen/snippets/system.py

When no spaces are allowed, don't show spaces in the placeholder.

Adjusted confusing placeholder.

---

mage2gen/snippets/system.py

Tested on Magento 2.3.1 (change order of "Source" and "Locale")

Fix for Currency Source Model

---

mage2gen/snippets/model.py

Mass action do not work because missing primary key define
**[krukas/Mage2Gen#280](https://github.com/krukas/Mage2Gen/issues/280): Mass action do not work because missing primary key define**
+ Add missing `$_idFieldName` in Collection class

[issue-280]: Fix missing $_idFieldName in Collection class

---

mage2gen/snippets/model.py

`db_schema.xml` built with `Entity ID` attribute `unsigned` value `true`
```xml
<?xml version="1.0" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Setup/Declaration/Schema/etc/schema.xsd">
<table comment="m2coach_storelocator_store Table" engine="innodb" name="m2coach_storelocator_store" resource="default">
<column comment="Entity Id" identity="true" name="store_id" nullable="false" padding="6" unsigned="true" xsi:type="smallint"/>
<constraint referenceId="PRIMARY" xsi:type="primary">
<column name="store_id"/>
</constraint>
<column identity="false" name="id" nullable="false" xsi:type="int"/>
</table>
</schema>
```
```xml
<?xml version="1.0" ?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" …
```

Entity ID field should be unsigned

---

mage2gen/snippets/plugin.py

When there are no arguments found for certain method of an around plugin, just pass the arguments using the splat operator. (makes the plugin work on non magento classes)

Proper fallback for creating an around plugin.

---

mage2gen/templates/class.tmpl
mage2gen/templates/interface.tmpl

Context: https://devdocs.magento.com/guides/v2.3/coding-standards/docblock-standard-general.html
1. `@author ,@category, @package, and @subpackage MUST NOT be used. Documentation is organized with the use of namespaces.`
1. Classes and interfaces should have a short description with a human-readable description of the class. If the short description adds no additional information beyond what the type name already supplies, the short description must be omitted.
Also - we live in the age of `strict_types` - so I introduced strict types to all new classes.

Follow Magento Coding standards

---

mage2gen/snippets/productattribute.py

Hi,
As commented in tickets:
* https://github.com/Mage2Gen/Mage2Gen/issues/346
* https://github.com/Mage2Gen/Mage2Gen/issues/327
* https://github.com/Mage2Gen/Mage2Gen/issues/309
The source_model of the boolean attribute shouldn't be empty, but Magento\Eav\Model\Entity\Attribute\Source\Boolean
I've modified the snippet adding this specific condition.

Set source_model for boolean product attribute

---

mage2gen/snippets/model.py

A setting is missing in the dataSource configuration when the indexField is not equal to `entity_id`. When paging through a grid, the results are cached by their IDs. Consequently, the resolving of the IDs will result unwanted behavior.
To set the indexField for the `Magento_Ui/js/grid/provider` component, the following setting has to be set:
``` xml
<dataSource component="Magento_Ui/js/grid/provider" name="...">
<settings>
<storageConfig>
<param name="indexField" xsi:type="string">...</param>
</storageConfig>
<updateUrl path="mui/index/render"/>
</settings>
</dataSource>
```

Fix cached paging not working properly

---

mage2gen/snippets/model.py

An ID field should support in default larger repositories. `smallint` only goes to 65.535 unsigned.
For smaller tables, the speed/resource benefit of smallint is also miniscule.

Change default ID field of model to `int` instead of `smallint`

---

mage2gen/snippets/model.py

[BUGFIX][BACI-567] New model snippet still uses _get() which doesn't work for extends of \Magento\Framework\Model\AbstractModel. Fixed getter function implementations by replacing it with the existing getData().
I can release januari 10th; but feel free to quick release if you feel like it :-)

[BUGFIX][BACI-567] New model snippet still uses _get()

---

mage2gen/snippets/controller.py

should fix https://github.com/Mage2Gen/Mage2Gen/issues/400 (can't test it)

fix minimum controller actionname length
